import type { BuildingTemplate, Mission, RegionProfile, RegionId } from "./types";

export const REGIONS: RegionProfile[] = [
  {
    id: "karachi-coastal",
    name: "Karachi Coastal Zone",
    biome: "coastal-urban",
    seismicRisk: 0.62,
    floodRisk: 0.88,
    wildfireRisk: 0.2,
    heatRisk: 0.82,
    windRisk: 0.74,
    droughtRisk: 0.48,
    slopeRisk: 0.14,
    baseRainfall: 260,
    averageTemp: 31,
    codeGuidance: [
      "Elevate foundations above flood return level",
      "Use corrosion-resistant structural reinforcement",
      "Include storm surge evacuation routes",
    ],
  },
  {
    id: "lahore-urban",
    name: "Lahore Dense Urban Core",
    biome: "dense-urban",
    seismicRisk: 0.42,
    floodRisk: 0.58,
    wildfireRisk: 0.35,
    heatRisk: 0.86,
    windRisk: 0.4,
    droughtRisk: 0.55,
    slopeRisk: 0.08,
    baseRainfall: 635,
    averageTemp: 33,
    codeGuidance: [
      "Prioritize passive cooling and reflective surfaces",
      "Improve drainage for intense monsoon bursts",
      "Maintain fire separation in dense blocks",
    ],
  },
  {
    id: "islamabad-hills",
    name: "Islamabad Hills",
    biome: "mixed-urban-hills",
    seismicRisk: 0.57,
    floodRisk: 0.52,
    wildfireRisk: 0.3,
    heatRisk: 0.54,
    windRisk: 0.46,
    droughtRisk: 0.36,
    slopeRisk: 0.44,
    baseRainfall: 1140,
    averageTemp: 27,
    codeGuidance: [
      "Design retaining walls for slope stability",
      "Enforce ductile detailing for seismic safety",
      "Protect hillside drainage channels from blockages",
    ],
  },
  {
    id: "gilgit-mountain",
    name: "Gilgit Mountain Belt",
    biome: "mountain",
    seismicRisk: 0.91,
    floodRisk: 0.49,
    wildfireRisk: 0.1,
    heatRisk: 0.32,
    windRisk: 0.61,
    droughtRisk: 0.2,
    slopeRisk: 0.88,
    baseRainfall: 200,
    averageTemp: 15,
    codeGuidance: [
      "Use lightweight roofs and seismic braces",
      "Avoid unstable slopes and landslide corridors",
      "Anchor critical infrastructure to bedrock where possible",
    ],
  },
  {
    id: "swat-valley",
    name: "Swat Valley",
    biome: "valley",
    seismicRisk: 0.79,
    floodRisk: 0.61,
    wildfireRisk: 0.22,
    heatRisk: 0.48,
    windRisk: 0.44,
    droughtRisk: 0.28,
    slopeRisk: 0.68,
    baseRainfall: 890,
    averageTemp: 23,
    codeGuidance: [
      "Reinforce masonry and avoid soft stories",
      "Stabilize slopes with vegetation and barriers",
      "Maintain evacuation roads for valley bottlenecks",
    ],
  },
  {
    id: "thar-desert",
    name: "Thar Desert Frontier",
    biome: "desert",
    seismicRisk: 0.31,
    floodRisk: 0.16,
    wildfireRisk: 0.4,
    heatRisk: 0.94,
    windRisk: 0.59,
    droughtRisk: 0.95,
    slopeRisk: 0.09,
    baseRainfall: 120,
    averageTemp: 37,
    codeGuidance: [
      "Use high-insulation and passive ventilation",
      "Deploy water harvesting and storage systems",
      "Design for dust storms and thermal stress",
    ],
  },
];

export const BUILDING_TEMPLATES: BuildingTemplate[] = [
  {
    id: "single-family",
    name: "Single-Family Home",
    category: "residential",
    cost: 120000,
    capacity: 6,
    baseResilience: 0.52,
    climateEfficiency: 0.48,
    fireSafety: 0.42,
    floodResistance: 0.4,
    seismicResistance: 0.35,
    description: "Affordable starter unit with moderate adaptability.",
  },
  {
    id: "elevated-home",
    name: "Elevated House",
    category: "residential",
    cost: 180000,
    capacity: 5,
    baseResilience: 0.66,
    climateEfficiency: 0.58,
    fireSafety: 0.45,
    floodResistance: 0.84,
    seismicResistance: 0.41,
    description: "Flood-adapted raised structure for water-prone zones.",
  },
  {
    id: "apartment-complex",
    name: "Apartment Complex",
    category: "residential",
    cost: 2500000,
    capacity: 120,
    baseResilience: 0.7,
    climateEfficiency: 0.6,
    fireSafety: 0.58,
    floodResistance: 0.56,
    seismicResistance: 0.64,
    description: "High-density housing with robust urban utility access.",
  },
  {
    id: "school",
    name: "Resilient School",
    category: "public",
    cost: 1800000,
    capacity: 800,
    baseResilience: 0.82,
    climateEfficiency: 0.72,
    fireSafety: 0.86,
    floodResistance: 0.73,
    seismicResistance: 0.81,
    description: "Critical community building designed for shelter operations.",
  },
  {
    id: "hospital",
    name: "Emergency Hospital",
    category: "public",
    cost: 5000000,
    capacity: 500,
    baseResilience: 0.88,
    climateEfficiency: 0.71,
    fireSafety: 0.91,
    floodResistance: 0.74,
    seismicResistance: 0.85,
    description: "Life-critical health hub with high code requirements.",
  },
  {
    id: "shelter",
    name: "Emergency Shelter",
    category: "public",
    cost: 800000,
    capacity: 1200,
    baseResilience: 0.79,
    climateEfficiency: 0.64,
    fireSafety: 0.75,
    floodResistance: 0.69,
    seismicResistance: 0.76,
    description: "Rapid-deployment shelter for displacement response.",
  },
  {
    id: "drainage",
    name: "Drainage System",
    category: "infrastructure",
    cost: 300000,
    capacity: 0,
    baseResilience: 0.61,
    climateEfficiency: 0.55,
    fireSafety: 0.2,
    floodResistance: 0.92,
    seismicResistance: 0.4,
    description: "Urban flood mitigation through runoff conveyance.",
  },
  {
    id: "flood-barrier",
    name: "Flood Barrier",
    category: "infrastructure",
    cost: 450000,
    capacity: 0,
    baseResilience: 0.68,
    climateEfficiency: 0.35,
    fireSafety: 0.1,
    floodResistance: 0.95,
    seismicResistance: 0.51,
    description: "Protects critical corridors from surge and overflow.",
  },
  {
    id: "solar-grid",
    name: "Solar Microgrid",
    category: "infrastructure",
    cost: 600000,
    capacity: 0,
    baseResilience: 0.56,
    climateEfficiency: 0.92,
    fireSafety: 0.44,
    floodResistance: 0.5,
    seismicResistance: 0.52,
    description: "Distributed clean energy for outage resilience.",
  },
  {
    id: "green-corridor",
    name: "Green Corridor",
    category: "infrastructure",
    cost: 150000,
    capacity: 0,
    baseResilience: 0.47,
    climateEfficiency: 0.85,
    fireSafety: 0.38,
    floodResistance: 0.49,
    seismicResistance: 0.15,
    description: "Cooling and runoff-absorbing ecological corridor.",
  },
];

export const CAMPAIGN_MISSIONS: Mission[] = [
  {
    id: "m1",
    title: "Retrofit Unsafe Hospital",
    description: "Upgrade a vulnerable hospital before an earthquake strike.",
    difficulty: "medium",
    reward: 520000,
    timeLimitMinutes: 45,
    status: "active",
    progress: 0.15,
    tags: ["earthquake", "health", "retrofit"],
    objectives: [
      { id: "m1o1", text: "Construct one Emergency Hospital", done: false },
      { id: "m1o2", text: "Reach engineering score above 65", done: false },
      { id: "m1o3", text: "Keep casualties below 2%", done: false },
    ],
  },
  {
    id: "m2",
    title: "Stop City Flooding",
    description: "Protect dense districts from monsoon-driven urban flooding.",
    difficulty: "hard",
    reward: 1200000,
    timeLimitMinutes: 60,
    status: "available",
    progress: 0,
    tags: ["flood", "drainage", "urban"],
    objectives: [
      { id: "m2o1", text: "Build two Drainage Systems", done: false },
      { id: "m2o2", text: "Build one Flood Barrier", done: false },
      { id: "m2o3", text: "Survive one flood simulation", done: false },
    ],
  },
  {
    id: "m3",
    title: "Rescue Wildfire Evacuation",
    description: "Coordinate emergency response in a fast-moving wildfire zone.",
    difficulty: "hard",
    reward: 950000,
    timeLimitMinutes: 40,
    status: "available",
    progress: 0,
    tags: ["wildfire", "rescue", "evacuation"],
    objectives: [
      { id: "m3o1", text: "Open at least two shelters", done: false },
      { id: "m3o2", text: "Deploy fire brigade operation", done: false },
      { id: "m3o3", text: "Reduce panic below 35", done: false },
    ],
  },
  {
    id: "m4",
    title: "Climate Resilient Megacity",
    description: "Balance heat, smog, flood, and seismic risks in one campaign.",
    difficulty: "expert",
    reward: 5000000,
    timeLimitMinutes: 120,
    status: "locked",
    progress: 0,
    tags: ["multi-hazard", "climate", "systems"],
    objectives: [
      { id: "m4o1", text: "Complete the first three missions", done: false },
      { id: "m4o2", text: "Reach resilience score above 80", done: false },
      { id: "m4o3", text: "Keep trust above 75 for 10 minutes", done: false },
    ],
  },
];

export function getRegionById(id: RegionId): RegionProfile {
  return REGIONS.find((region) => region.id === id) ?? REGIONS[0];
}
